import { Score } from './supabase'

export const mockScores: Score[] = [
  {
    id: '1',
    handle: 'task-orchestrator',
    overall: 87,
    agents: 12,
    quality: 13,
    autonomy: 12,
    safety: 13,
    memory: 8,
    skills: 8,
    infra: 8,
    security: 4,
    domain: 5,
    scanner_version: '1.0.0',
    metadata: {
      agent_count: 40,
      skill_count: 22,
      mcp_count: 16,
      domain_detected: 'ML/Quant',
    },
    created_at: '2026-03-20T12:00:00Z',
  },
  {
    id: '2',
    handle: 'fullstack-pro',
    overall: 72,
    agents: 8,
    quality: 11,
    autonomy: 10,
    safety: 11,
    memory: 7,
    skills: 7,
    infra: 7,
    security: 4,
    domain: 3,
    scanner_version: '1.0.0',
    metadata: {
      agent_count: 15,
      skill_count: 10,
      mcp_count: 8,
      domain_detected: 'Web Development',
    },
    created_at: '2026-03-19T15:30:00Z',
  },
  {
    id: '3',
    handle: 'data-pipeline',
    overall: 64,
    agents: 6,
    quality: 10,
    autonomy: 9,
    safety: 10,
    memory: 6,
    skills: 6,
    infra: 6,
    security: 3,
    domain: 4,
    scanner_version: '1.0.0',
    metadata: {
      agent_count: 10,
      skill_count: 8,
      mcp_count: 5,
      domain_detected: 'Data Engineering',
    },
    created_at: '2026-03-19T10:00:00Z',
  },
  {
    id: '4',
    handle: 'minimal-setup',
    overall: 38,
    agents: 3,
    quality: 5,
    autonomy: 5,
    safety: 6,
    memory: 4,
    skills: 4,
    infra: 4,
    security: 2,
    domain: 1,
    scanner_version: '1.0.0',
    metadata: {
      agent_count: 2,
      skill_count: 3,
      mcp_count: 2,
      domain_detected: 'General',
    },
    created_at: '2026-03-18T08:00:00Z',
  },
  {
    id: '5',
    handle: 'security-first',
    overall: 79,
    agents: 9,
    quality: 12,
    autonomy: 11,
    safety: 14,
    memory: 7,
    skills: 6,
    infra: 7,
    security: 5,
    domain: 4,
    scanner_version: '1.0.0',
    metadata: {
      agent_count: 20,
      skill_count: 14,
      mcp_count: 10,
      domain_detected: 'Security/DevOps',
    },
    created_at: '2026-03-18T22:15:00Z',
  },
  {
    id: '6',
    handle: 'creative-studio',
    overall: 53,
    agents: 5,
    quality: 8,
    autonomy: 7,
    safety: 8,
    memory: 5,
    skills: 5,
    infra: 5,
    security: 3,
    domain: 3,
    scanner_version: '1.0.0',
    metadata: {
      agent_count: 8,
      skill_count: 6,
      mcp_count: 4,
      domain_detected: 'Creative/Design',
    },
    created_at: '2026-03-17T16:45:00Z',
  },
]
